# -*- coding: utf-8 -*-
"""etl netflix primera parte

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cS1uqC6dkkH3KlsnBgq1Na9_YLJ3Jow
"""

import pandas as pd  #abre el archivo, separa columnas, identifica filas y crea una tabla de datos.
import numpy as np #sirve para trabajar con cálculos matemáticos y arreglos de datos de manera rapida.

!pip install openpyxl

from google.colab import files #con este estamos cargando el excel

uploaded = files.upload()

df = pd.read_excel("Copia de netflix_files_.xlsx") # lee el excel

df.head() #muestra la info en general , como los datos y yap (Muestra las primeras cinco filas y sirve para verificar si se cargo el archivo)

df.info() #Muestra información general del DataFrame.

df.describe() #Calcula estadísticas para las columnas numéricas.

df = df.dropna()   #esto es para las filas vacias (eliminacion), no te olvides alisson

df.columns = ["id de la pelicula o serie", "tipo", "titulo", "director", "reparto", "país", "fecha de incorporación","año de lanzamiento", "raiting", "duración" , "listado en", "descripción", "década"]

df = df.drop_duplicates()

print(df.columns.tolist()) #leer todos los nombres pa copiar bien despues

df["año de lanzamiento"] = pd.to_numeric(df["año de lanzamiento"], errors="coerce") #aqui ya quedo definido como numero

df["año de lanzamiento"].dtype #definir cual es el tipo de dato

df["década"] = ((df["año de lanzamiento"] // 10) * 10).astype("Int64") #arrojar el resultado como numero entero

df.head()

len(df) #cuenta el número de filas (registros) del DataFrame.

df.isnull().sum() #Cuenta cuántos valores nulos (vacíos) hay en cada columna.