-- R2 creacion de la base de datos
-- drop database if exists dronandes;

-- create database dronandes;
drop schema if exists dronandes cascade;
create schema dronandes;
set search_path to dronandes;

-- creacion de tablas por prioridad
create table bases (
    idbase          int generated by default as identity primary key,
    nombre           varchar(60) not null unique,
    municipio        varchar(60) not null,
    departamento     varchar(40) not null,
    capacidaddrones int not null,
    fechaapertura   date not null,
    constraint chk_basescapacidad check (capacidaddrones > 0)
);

create table tiposcarga (
    idtipo       int generated by default as identity primary key,
    nombre        varchar(40) not null unique,
    tarifakg     decimal(10,2) not null,
    requierefrio boolean not null default false,
    constraint chk_tiposcargatarifa check (tarifakg > 0)
);

create table drones (
    iddron           int generated by default as identity primary key,
    codigoserie      varchar(12) not null unique,
    modelo            varchar(40) not null,
    cargamax_kg      decimal(5,2) not null,
    autonomia_km      decimal(5,1) not null,
    estado            varchar(15) not null default 'ACTIVO',
    horasvuelo       decimal(7,1) not null default 0,
    fechaadquisicion date not null,
    idbase           int not null,
    constraint chk_dronesautonomia check (autonomia_km > 0),
    constraint chk_dronesestado    check (estado in ('ACTIVO', 'MANTENIMIENTO', 'RETIRADO')),
    constraint chk_droneshoras     check (horasvuelo >= 0),
    constraint fk_dronesbase foreign key (idbase) references bases (idbase)
);

create table pilotos (
    idpiloto     int generated by default as identity primary key,
    documento     varchar(15) not null unique,
    nombres       varchar(50) not null,
    apellidos     varchar(50) not null,
    email         varchar(80) not null unique,
    licencia      char(1) not null,
    fechaingreso date not null,
    idsupervisor int null,
    idbase       int not null,
    constraint chk_pilotoslicencia check (licencia in ('A', 'B', 'C')),
    constraint fk_pilotosbase foreign key (idbase) references bases (idbase)
);

create table clientes (
    idcliente     int generated by default as identity primary key,
    tipo           varchar(12) not null,
    nombre         varchar(80) not null,
    nit_o_documento  varchar(15) not null unique,
    email          varchar(80) null unique,
    telefono       varchar(15) null,
    municipio      varchar(60) not null,
    fecharegistro timestamp default current_timestamp,
    constraint chk_clientestipo check (tipo in ('HOSPITAL', 'FARMACIA', 'COMERCIO', 'ONG', 'PERSONA'))
);


create table entregas (
    identrega        int generated by default as identity primary key,
    codigo            varchar(10) not null unique,
    idcliente        int not null,
    iddron           int not null,
    idpiloto         int not null,
    fechaprogramada  timestamp not null,
    fechaentrega     timestamp null,
    municipiodestino varchar(60) not null,
    distancia_km      decimal(5,1) not null,
    prioridad         varchar(8) not null default 'NORMAL',
    estado            varchar(12) not null default 'PROGRAMADA',
    calificacion      smallint null,
    constraint chk_entregasdistancia     check (distancia_km > 0),
    constraint chk_entregasprioridad     check (prioridad in ('NORMAL', 'URGENTE', 'VITAL')),
    constraint chk_entregasestado        check (estado in ('PROGRAMADA', 'EN_VUELO', 'ENTREGADA', 'CANCELADA', 'FALLIDA')),
    constraint chk_entregascalificacion  check (calificacion between 1 and 5),
    constraint chk_entregasfechaentrega check (fechaentrega is null or estado = 'ENTREGADA'),
    constraint fk_entregascliente foreign key (idcliente) references clientes (idcliente),
    constraint fk_entregasdron    foreign key (iddron)    references drones (iddron),
    constraint fk_entregaspiloto  foreign key (idpiloto)  references pilotos (idpiloto)
);


create table carga_entrega (
    primary key (identrega, idtipo),
    identrega int not null,
    idtipo    int not null,
    peso_kg    decimal(6,2) not null,
    unidades   int not null default 1,
    constraint chk_cargaentregapeso     check (peso_kg > 0),
    constraint chk_cargaentregaunidades check (unidades > 0),
    constraint fk_cargaentregaentrega foreign key (identrega) references entregas (identrega),
    constraint fk_cargaentregatipo    foreign key (idtipo)    references tiposcarga (idtipo)
);

create table mantenimientos (
    idmantenimiento int generated by default as identity primary key,
    iddron          int not null,
    fecha            date not null,
    tipo             varchar(12) not null,
    descripcion      varchar(200) null,
    costo            decimal(10,2) not null,
    constraint chk_mantenimientostipo  check (tipo in ('PREVENTIVO', 'CORRECTIVO')),
    constraint chk_mantenimientoscosto check (costo >= 0),
    constraint fk_mantenimientosdron foreign key (iddron) references drones (iddron)
);

create table historialentregas (
    idhistorial    int generated by default as identity primary key,
    identrega      int not null,
    estadoanterior varchar(12) not null,
    estadonuevo    varchar(12) not null,
    fechacambio    timestamp not null default current_timestamp,
    constraint fk_historialentregasentrega foreign key (identrega) references entregas (identrega)
);


-- DATOS INICIALES — Proyecto Cóndor (DronAndes Express S.A.S.)
-- Corte: 30 de septiembre de 2026, 18:00
-- Script COMÚN para MySQL y PostgreSQL. Ejecutar DESPUÉS del DDL (R2).

insert into  bases (idbase, nombre, municipio, departamento, capacidaddrones,
fechaapertura) values
(1, 'Base Cóndor', 'Rionegro', 'Antioquia', 6, '2024-02-15'),
(2, 'Base Colibrí', 'Guatapé', 'Antioquia', 4, '2024-08-01'),
(3, 'Base Frailejón', 'Tunja', 'Boyacá', 5, '2025-01-20'),
(4, 'Base Guadua', 'Salento', 'Quindío', 3, '2026-07-01');
insert into tiposcarga (idtipo, nombre, tarifakg, requierefrio) values
(1, 'Vacunas', 12000, TRUE),
(2, 'Muestras de laboratorio', 10000, TRUE),
(3, 'Medicamentos', 8000, FALSE),
(4, 'Documentos', 5000, FALSE),
(5, 'Repuestos', 4500, FALSE),
(6, 'Alimentos', 3500, FALSE);
insert into drones (iddron, codigoserie, modelo, cargamax_kg, autonomia_km, estado,
horasvuelo, fechaadquisicion, idbase) values
(1, 'DA-CX4-01', 'Cóndor X4', 8.00, 45.0, 'ACTIVO', 312.5, '2024-02-20', 1),
(2, 'DA-CX4-02', 'Cóndor X4', 8.00, 45.0, 'ACTIVO', 468.0, '2024-03-10', 1),
(3, 'DA-CX6-01', 'Cóndor X6', 15.00, 60.0, 'ACTIVO', 205.0, '2025-01-15', 1),
(4, 'DA-COL-01', 'Colibrí Mini', 2.50, 25.0, 'ACTIVO', 520.5, '2024-08-05', 2),
(5, 'DA-COL-02', 'Colibrí Mini', 2.50, 25.0, 'MANTENIMIENTO', 610.0, '2024-08-05', 2),
(6, 'DA-ALB-01', 'Albatros H8', 25.00, 90.0, 'ACTIVO', 98.0, '2025-02-01', 3),
(7, 'DA-CX6-02', 'Cóndor X6', 15.00, 60.0, 'ACTIVO', 150.5, '2025-03-12', 3),
(8, 'DA-ALB-02', 'Albatros H8', 25.00, 90.0, 'RETIRADO', 890.0, '2024-05-01', 3);
-- Los supervisores (id_supervisor NULL) se insertan primero.
insert into pilotos (idpiloto, documento, nombres, apellidos, email, licencia, fechaingreso,
idsupervisor, idbase) values
(1, '1036600111', 'Laura', 'Restrepo Gil', 'laura.restrepo@dronandes.co', 'C', '2024-02-01', NULL,
1),
(2, '1049600222', 'Camilo', 'Duarte Rojas', 'camilo.duarte@dronandes.co', 'C', '2025-01-10', NULL,
3),
(3, '1036600333', 'Mateo', 'Zapata Vélez', 'mateo.zapata@dronandes.co', 'B', '2024-04-15', 1, 1),
(4, '1036600444', 'Sara', 'Montoya Ruiz', 'sara.montoya@dronandes.co', 'B', '2024-08-10', 1, 2),
(5, '1036600555', 'Julián', 'Patiño Cruz', 'julian.patino@dronandes.co', 'A', '2025-06-01', 1, 2),
(6, '1049600666', 'Daniela', 'Suárez León', 'daniela.suarez@dronandes.co', 'B', '2025-02-01', 2, 3),
(7, '1049600777', 'Tomás', 'Becerra Niño', 'tomas.becerra@dronandes.co', 'A', '2026-06-15', 2, 3);
insert into clientes (idcliente, tipo, nombre, nit_o_documento, email, telefono, municipio,
fecharegistro) values
(1, 'HOSPITAL', 'Hospital San Juan de Dios de Rionegro', '890980000-1', 'compras@hsjdrionegro.org',
'6045310000', 'Rionegro', '2024-03-01'),
(2, 'FARMACIA', 'Droguería La Esperanza', '71234567', 'esperanza.drogueria@gmail.com',
'3104567890', 'Guatapé', '2024-09-12'),
(3, 'HOSPITAL', 'E.S.E. Hospital San Rafael de Tunja', '891800231-6', 'Logistica@HSRTunja.gov.co',
'6087405050', 'Tunja', '2025-01-25'),
(4, 'ONG', 'Fundación Alas para el Campo', '900456789-2', 'contacto@alasparaelcampo.org',
NULL, 'Marinilla', '2024-11-03'),
(5, 'COMERCIO', 'Repuestos Agrícolas El Arriero', '900123456-7', NULL, '31245678',
'El Peñol', '2025-04-18'),
(6, 'PERSONA', 'Mariana Gómez Arango', '1040123456', 'mariana.gomez@hotmail.com',
'3157778899', 'Guarne', '2025-07-07'),
(7, 'FARMACIA', 'Farmacia Botica del Páramo', '900777888-1', 'boticaparamo@gmail.com',
'3209998877', 'Ventaquemada', '2025-02-14'),
(8, 'COMERCIO', 'Café de Altura Las Nubes', '901222333-4', 'ventas@cafelasnubes.co',
'3001112233', 'Salento', '2026-07-20'),
(9, 'PERSONA', 'Jorge Iván Ríos', '79888777', NULL, NULL, 'Rionegro',
'2026-08-30'),
(10, 'ONG', 'Corporación Montaña Viva', '900999111-0', 'info@montanaviva.org',
'310555444', 'Sáchica', '2025-09-01');
insert into entregas (identrega, codigo, idcliente, iddron, idpiloto, fechaprogramada,
fechaentrega, municipiodestino, distancia_km, prioridad, estado, calificacion) values
(1, 'ENT-0001', 1, 1, 3, '2026-08-03 08:00:00', '2026-08-03 08:42:00', 'San Vicente', 18.5, 'VITAL',
'ENTREGADA', 5),
(2, 'ENT-0002', 1, 3, 1, '2026-08-05 09:30:00', '2026-08-05 10:20:00', 'Concepción', 32.0,
'VITAL', 'ENTREGADA', 4),
(3, 'ENT-0003', 2, 4, 4, '2026-08-07 14:00:00', '2026-08-07 14:25:00', 'San Rafael', 12.0,
'NORMAL', 'ENTREGADA', 5),
(4, 'ENT-0004', 4, 2, 3, '2026-08-10 07:45:00', '2026-08-10 08:30:00', 'El Carmen de Viboral', 22.4,
'URGENTE', 'ENTREGADA', 3),
(5, 'ENT-0005', 5, 3, 1, '2026-08-12 11:00:00', NULL, 'El Peñol', 15.0, 'NORMAL',
'CANCELADA', NULL),
(6, 'ENT-0006', 3, 6, 2, '2026-08-14 06:30:00', '2026-08-14 07:40:00', 'Ramiriquí', 48.0, 'VITAL',
'ENTREGADA', 5),
(7, 'ENT-0007', 10, 7, 6, '2026-08-18 10:00:00', '2026-08-18 10:35:00', 'Samacá', 20.5,
'NORMAL', 'ENTREGADA', 4),
(8, 'ENT-0008', 3, 8, 6, '2026-08-20 08:15:00', NULL, 'Chíquiza', 35.0, 'URGENTE',
'FALLIDA', NULL),
(9, 'ENT-0009', 6, 4, 5, '2026-08-22 16:00:00', '2026-08-22 16:20:00', 'Guarne', 9.5, 'NORMAL',
'ENTREGADA', 2),
(10, 'ENT-0010', 1, 1, 1, '2026-08-25 07:00:00', '2026-08-25 07:50:00', 'Sonsón', 41.0, 'VITAL',
'ENTREGADA', 5),
(11, 'ENT-0011', 10, 6, 2, '2026-08-27 09:00:00', '2026-08-27 10:05:00', 'Sáchica', 52.5,
'URGENTE', 'ENTREGADA', NULL),
(12, 'ENT-0012', 2, 5, 4, '2026-08-29 13:00:00', NULL, 'Alejandría', 14.0, 'NORMAL',
'CANCELADA', NULL),
(13, 'ENT-0013', 4, 2, 1, '2026-09-01 08:00:00', '2026-09-01 08:55:00', 'Granada', 38.0,
'URGENTE', 'ENTREGADA', 4),
(14, 'ENT-0014', 1, 3, 1, '2026-09-03 10:30:00', '2026-09-03 11:15:00', 'Abejorral', 44.0, 'VITAL',
'ENTREGADA', 5),
(15, 'ENT-0015', 7, 7, 6, '2026-09-08 15:00:00', '2026-09-08 15:30:00', 'Turmequé', 17.0,
'NORMAL', 'ENTREGADA', 3),
(16, 'ENT-0016', 3, 6, 2, '2026-09-15 06:00:00', '2026-09-15 07:10:00', 'Miraflores', 58.0, 'VITAL',
'ENTREGADA', 4),
(17, 'ENT-0017', 6, 2, 3, '2026-09-21 17:00:00', NULL, 'Guarne', 10.0, 'NORMAL',
'CANCELADA', NULL),
(18, 'ENT-0018', 10, 7, 6, '2026-09-30 17:40:00', NULL, 'Villa de Leyva', 26.0, 'NORMAL',
'EN_VUELO', NULL),
(19, 'ENT-0019', 1, 1, 1, '2026-10-01 07:30:00', NULL, 'Nariño', 47.0, 'VITAL',
'PROGRAMADA', NULL),
(20, 'ENT-0020', 3, 6, 6, '2026-10-02 06:00:00', NULL, 'Pesca', 39.0, 'VITAL',
'PROGRAMADA', NULL);
insert into carga_entrega (identrega, idtipo, peso_kg, unidades) values
(1, 1, 3.00, 60), (1, 3, 2.00, 15),
(2, 2, 1.50, 30), (2, 3, 4.00, 40),
(3, 3, 1.80, 12),
(4, 3, 3.50, 25), (4, 4, 0.50, 3),
(5, 5, 6.00, 4),
(6, 1, 5.00, 100), (6, 2, 2.00, 40),
(7, 3, 6.00, 50),
(8, 1, 8.00, 160), (8, 3, 4.00, 30),
(9, 4, 0.80, 5),
(10, 1, 4.00, 80), (10, 2, 1.00, 20), (10, 3, 2.50, 20),
(11, 3, 7.00, 60), (11, 4, 1.00, 6),
(13, 3, 5.00, 40), (13, 5, 2.00, 2),
(14, 1, 6.00, 120), (14, 2, 3.00, 60),
(15, 3, 3.00, 25), (15, 4, 0.30, 2),
(16, 1, 10.00, 200), (16, 3, 8.00, 70),
(18, 3, 4.00, 35),
(19, 1, 3.50, 70),
(20, 2, 2.50, 50), (20, 1, 6.00, 120);
insert into mantenimientos (idmantenimiento, iddron, fecha, tipo, descripcion, costo) values
(1, 2, '2026-03-15', 'PREVENTIVO', 'Cambio de hélices', 350000),
(2, 4, '2026-04-02', 'PREVENTIVO', 'Calibración de GPS', 180000),
(3, 5, '2026-09-25', 'CORRECTIVO', 'Falla en motor 3', 1250000),
(4, 8, '2026-08-21', 'CORRECTIVO', 'Impacto en aterrizaje, evaluación de daños', 2800000),
(5, 1, '2026-06-10', 'PREVENTIVO', 'Revisión general de 300 horas', 420000),
(6, 6, '2026-07-05', 'PREVENTIVO', NULL, 260000),
(7, 5, '2026-05-14', 'PREVENTIVO', 'Cambio de baterías', 950000),
(8, 2, '2026-09-12', 'CORRECTIVO', 'Sensor de altitud defectuoso', 610000);
-- solo postgresql: sincroniza las secuencias con los identificadores insertados de forma explicita
select setval(pg_get_serial_sequence('bases','idbase'), (select max(idbase) from bases));
select setval(pg_get_serial_sequence('tiposcarga','idtipo'), (select max(idtipo) from tiposcarga));
select setval(pg_get_serial_sequence('drones','iddron'), (select max(iddron) from drones));
select setval(pg_get_serial_sequence('pilotos','idpiloto'), (select max(idpiloto) from pilotos));
select setval(pg_get_serial_sequence('clientes','idcliente'), (select max(idcliente) from clientes));
select setval(pg_get_serial_sequence('entregas','identrega'), (select max(identrega) from entregas));
select setval(pg_get_serial_sequence('mantenimientos','idmantenimiento'), (select max(idmantenimiento) from mantenimientos));
